media_entity_kaltura.settings:
  type: config_object
  label: 'Media source Kaltura settings'
  mapping:
    partner_id:
      type: string
      label: 'Default Kaltura partner ID'
    ui_conf_id:
      type: string
      label: 'Default Kaltura UI Conf ID'
    server_url:
      type: uri
      label: 'Kaltura server URL'
    admin_secret:
      type: string
      label: 'Admin secret'

media.source.kaltura:
  type: media.source.field_aware
  label: '"Kaltura" media source configuration'
  mapping:
    thumbnails_directory:
      type: uri
      label: 'URI of thumbnail storage directory'

field.formatter.settings.kaltura_embed:
  type: mapping
  mapping:
   width:
    type: integer
    label: 'Player width in pixels'
   height:
    type: integer
    label: 'Player height in pixels'
